set -g mouse on

# Vi mode
set -g mode-keys vi

# resize the pane
bind -r < resize-pane -L 5
bind -r > resize-pane -R 5
bind -r - resize-pane -D 5
bind -r + resize-pane -U

# Move between panes using vim-like
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Allow passing focus state
set-option -g focus-events on

set -s copy-command 'pbcopy'

