set-window-option -g mouse off

set -g @scroll-speed-num-lines-per-scroll 1

set-option -sa terminal-overrides ",$TERM:RGB"
set-option -g default-terminal "screen-256color"
set-option -sg escape-time 10

# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize the pane
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

setw -g mode-keys vi

set -g base-index 1
setw -g pane-base-index 1

set-option -g focus-events on

# Bind selection keys (v and Space)
bind-key -T copy-mode-vi Space send-keys -X begin-selection
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm'
