vim.opt.inccommand = "split"
vim.opt.lazyredraw = true
vim.opt.ignorecase = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.autoindent = true -- copy indent from last line when inserting new line
vim.opt.smartindent = true -- indent in braces and other things
vim.opt.smarttab = true -- insert tabs with shiftwidth value
vim.opt.tabstop = 2 -- tab size
vim.opt.shiftwidth = 2 -- indentation size
vim.opt.expandtab = true -- replace tabs with spaces
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 7
vim.opt.colorcolumn = "80"
vim.opt.hid = true
vim.opt.termguicolors = true -- this makes colors work properly
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.showmode = false -- don't show text displaying mode (airline replaces this)
vim.opt.shell = "/bin/bash"
vim.g.mapleader = ","
vim.api.nvim_command "colorscheme gruvbox-baby"
-- set background=dark
-- let g:gruvbox_material_background = 'medium'
-- let g:gruvbox_material_better_performance = 1
